### ISSUE TITLE
having a bar drawer for anything

### ISSUE THREAD

**Issue by Ticonderoga** [scorzy/CLW#1]
Hello,

I would like to use your CLW to print my task from taskwarrior and usually I use a progress bar to see how much the task is fullfilled ... is it possible ?

**Comment by scorzy** [comment]
Hello,
Not possible for now, however i like the idea.
I will add bar drawer for anything in next release. (for anything i mean a command which return a number, or a fixed number )

**Comment by scorzy** [comment]
Added in version 1.0.9, accept number and command which return a number from 0 to 100
https://github.com/scorzy/CLW/wiki/Bar

**Comment by Ticonderoga** [comment]
Fantastic ... As soon as my task list is done I sent you a screenshot !! Thanks a lot !
